### ISSUE TITLE
trusted certificate entries are not password-protected

### ISSUE THREAD

**Issue by dzhai** [CyberSource/cybersource-sdk-java#14]
Error log：
-------------------------------------------------------------------------------
Test set: com.cybersource.ws.client.ApacheWssjSignatureIT
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.031 sec <<< FAILURE!
testSoapWrapAndSign(com.cybersource.ws.client.ApacheWssjSignatureIT)  Time elapsed: 0.031 sec  <<< ERROR!
java.lang.UnsupportedOperationException: trusted certificate entries are not password-protected
	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:466)
	at java.security.KeyStore.getEntry(KeyStore.java:1290)
	at com.cybersource.ws.client.ApacheSignatureWrapper.readAndStoreCertificateAndPrivateKey(ApacheSignatureWrapper.java:237)
	at com.cybersource.ws.client.ApacheSignatureWrapper.loadMerchantP12File(ApacheSignatureWrapper.java:181)
	at com.cybersource.ws.client.ApacheSignatureWrapper.soapWrapAndSign(ApacheSignatureWrapper.java:76)
	at com.cybersource.ws.client.ApacheWssjSignatureIT.testSoapWrapAndSign(ApacheWssjSignatureIT.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)

-------------------------------------
### link  [Generating Transaction Keys]( http://apps.cybersource.com/library/documentation/dev_guides/security_keys/html/wwhelp/wwhimpl/js/html/wwhelp.htm#href=securityKeys_SO_API.4.2.html)

**Comment by dzhai** [comment]
fixed

**Comment by cougil** [comment]
Hi!
We are receiving the same exception trying to use a test Transaction Key generated by the Cybersource Business center but using the Simple Order API. 
What we have done is try to use the Test Business Center, generate our keys (download them) and copy it (and setup the merchant ID + password) in the folder with the Samples you've in your repository.
What we are doing wrong?
Best,

**Comment by zhaojinghua** [comment]
keyAlias=<merchantID>

**Comment by zhaojinghua** [comment]
keyAlias=merchantID
