### ISSUE TITLE
Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.

### ISSUE THREAD

**Issue by deveshrastogi** [CyberSource/cybersource-sdk-java#44]
at org.apache.commons.logging.impl.LogFactoryImpl.getLogConstructor(LogFactoryImpl.java:385)
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:529)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:235)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:209)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:351)
	at org.apache.ws.security.components.crypto.AbstractCrypto.<clinit>(AbstractCrypto.java:56)
	at com.cybersource.ws.client.BaseMessageHandler.<init>(BaseMessageHandler.java:23)
	at com.cybersource.ws.client.SignedAndEncryptedMessageHandler.<init>(SignedAndEncryptedMessageHandler.java:51)
	at com.cybersource.ws.client.SignedAndEncryptedMessageHandler.getInstance(SignedAndEncryptedMessageHandler.java:62)
	at com.cybersource.ws.client.Client.soapWrapAndSign(Client.java:198)
	at com.cybersource.ws.client.Client.runTransaction(Client.java:113)
	at com.cybersource.ws.client.Client.runTransaction(Client.java:69)
	at juspay.CybersourceGatewayService.runAuth(CybersourceGatewayService.groovy:204)

**Comment by mahendya** [comment]
Your stacktrace does not provide much information.
How you are able to see two version's of org.apache.commons.logging.Log' ? can you please provide some more info and which version of cybersource-sdk-java you are trying ?

With cybersource-sdk-java-6.2.1 release, only commons-logging-1.0.3.jar is getting used as a dependency.

If you are using some other version of commons-logging in your pom then you can put exclusion and then only one jar should be used.
